- hosts: all
  vars_files:
    - users.yml
  tasks:
    - name: Display file
      debug: msg="his file contains "
    - name: Pause play until a URL is reachable from this host
      debug:
        msg: "{{ item.name }}"
      with_items: "{{ users }}"
    - name: Add the user 'johnd' with a specific uid and a primary group of 'admin'
      user:
        name: "{{ item.name }}"
        comment: " {{ item.name }} {{item.middle}} {{item.last }}"
        group: item.group
        password:  "{{ lookup('password', '/tmp/passwordfile chars=digits length=8 encrypt=sha1') }}"
      with_items: "{{ users }}"
