- hosts: all
  vars_files:
    - users.yml
  tasks:
    - name: Display file
      debug: msg="his file contains "
    - name: Pause play until a URL is reachable from this host
      debug:
        msg: "{{ item.name }}"
      with_items: "{{ users }}"
    - name: Add the user 
      user:
        name: "{{ item.name }}"
        comment: " {{ item.name }} {{ item.middle}} {{item.lastname}} "
        group: item.group
        password:  "{{ lookup('password', '/tmp/passwordfile chars=digits length=8 encrypt=sha1_crypt') }}"
      with_items: "{{ users }}"
