- hosts: all
  vars_files:
    - users.yml
  tasks:
    - name: Ensure group "somegroup" exists
      group:
        name: "{{ item.groups }}"
        state: present
      with_items: "{{ users }}"
      tags:
        - groupCreat
        - never
    - name: Add the user 
      user:
        name: "{{ item.name }}"
        comment: "{{ item.name }} {{ item.middle}} {{item.lastname}}"
        group: "{{ item.groups }}"
        password:  "{{ lookup('password', '/root/passwdFiles-' + item.name + ' chars=digits length=8 encrypt=md5_crypt') }}"
      with_items: "{{ users }}"
