- hosts: all
  vars_files:
    - users.yml
  tasks:
    - name: Display file
      debug: msg="his file contains "
    - name: Pause play until a URL is reachable from this host
      uri:
        url: "https://{{ item.name }}"
        follow_redirects: none
        method: GET
      loop: "{{ users }}"
