- hosts: all
  vars:
          fileWeb: "{{ lookup('file', 'users.yml').splitlines()|map('from_yaml')|list}}"
  tasks:
    - name: Display file
      debug: msg="his file contains {{ fileWeb }}"
    - name: Pause play until a URL is reachable from this host
      uri:
        url: "https://{{ item.name }}"
        follow_redirects: none
        method: GET
      loop: "{{  lookup('dict', fileWeb) }}"
