- hosts: all
  vars:
          fileWeb: "{{ lookup('file','testConnection.yml').splitlines() | list }}"
  tasks:
    - name: Display file
      debug: msg="his file contains {{ fileWeb }}"
    - name: Pause play until a URL is reachable from this host
      uri:
        url: "https://{{ item }}"
        follow_redirects: none
        method: GET
      loop: "{{ fileWeb }}"
