- hosts: localhost
  vars_files:
    - files.yml
  tasks:  
    - name: Use sha1 to calculate checksum
      stat:
         path: "{{ item.path }}"
         checksum_algorithm: sha1
      register: result
      failed_when: "result.stat.checksum != item.checksum " 
      with_items: "{{ files }}"
