- name: update all packages
  hosts: "{{ hosts }}"
  tasks:
    - name: run yum update
      yum:
         name: "*"
         state: latest
    - name: rebooting if requried
      reboot:
      when: "{{rebooting}}"
         
         
      
  
